#!/bin/sh

result=0

echo 'fizzbuzz test'

for name in fizzbuzz.*
do
	ext="$( echo "$name" | grep -Eo '\.[^\.]+$' | tr '.' ' ' )"
	[ -z "$ext" ] && continue
	printf '%s ' $ext
	if "./$name" | diff - expected > /dev/null 2>&1
	then
		printf %s pass
	else
		printf %s fail
		result=1
	fi
	printf '\n'
done

exit $result
