#!/bin/sh

_main() {
	trap _exit INT TERM

	RESULT=0
	PATH="$( readlink -f "$0" ):$PATH"
	TMP_FILES="$( _mktmpfile )"

	if [ -n "$1" ] && [ -x "$1" ]
	then
		_test "$1"
	else
		for filename in fizzbuzz.*
		do
			_test "$filename" &
		done

		wait
	fi

	_exit $RESULT
}

_add_tmp_file() {
	file="$( _mktmpfile )"
	echo "$file" >> "$TMP_FILES"
	echo "$file"
}

_cleanup() {
	[ -z "$TMP_FILES" ] && return
	[ ! -f "$TMP_FILES" ] && return

	while read -r file
	do
		[ ! -f "$file" ] && continue
		rm "$file"
	done < "$TMP_FILES"

	rm "$TMP_FILES"
}

_exit() {
	exit_code=$?
	_cleanup
	[ $# -gt 0 ] && exit "$1"
	exit $exit_code
}

_mktmpfile() {
	mktemp -t "$( basename "$0" )"
}

_test() {
	name="$1"
	ext="$( echo "$name" | grep -Eo '\.[^\.]+$' | tr -d '.' )"

	[ "$ext" = "txt" ] && return
	[ -z "$ext" ] && return 1

	tmp_file="$( _add_tmp_file )"
	expected="$( basename "$name" ".$ext" ).txt"

	"./$name" > "$tmp_file" 2>/dev/null

	code=$?

	if [ $code -eq 127 ]
	then
		echo "$name WARN: Interpreter not installed."
	else
		if match "$tmp_file" "$expected"
		then
			echo "$name PASS"
		else
			echo "$name FAIL"
			RESULT=1
		fi
	fi

	rm "$tmp_file"
}

_main "$@"
